- name: ollama_chat/qwen3:32b-q8_0
  edit_format: diff
  use_repo_map: true
  use_temperature: 0.7
  extra_params:
    top_p: 0.8
    top_k: 20
    min_p: 0.0
    temperature: 0.7
    max_tokens: 32768
    num_ctx: 32768
    num_predict: 16384
  weak_model_name: ollama_chat/devstral:24b-small-2505-q8_0
  editor_model_name: ollama_chat/devstral:24b-small-2505-q8_0
  editor_edit_format: editor-diff
