- model_id: azure/gpt-4o-mini
  model_name: gpt-4o-mini
  api_base: https://erpipehe-openai.openai.azure.com/
  api_version: '2024-12-01-preview'
  vision: true
  can_stream: true
  supports_tools: true

- model_id: azure/o4-mini
  model_name: o4-mini
  api_base: https://erpipehe-openai.openai.azure.com/
  api_version: '2024-12-01-preview'
  reasoning: true
  can_stream: true
  supports_tools: true

- model_id: azure/text-embedding-3-small
  embedding_model: true
  model_name: text-embedding-3-small
  api_base: https://erpipehe-openai.openai.azure.com/
  api_version: '2024-12-01-preview'
